### ISSUE TITLE
Exported resources don't ensure unique names

### ISSUE THREAD

**Issue by thrnio** [mattkirby/puppet-zpr#28]
Currently, all the exported resources use the resource title of the defined type resource specified on the end node. There is no way to guarantee that this is unique across nodes, which means multiple nodes can define the same exported resource, which will break compiles on at least the worker node.

All exported resources should include `$hostname`, `$fqdn`, or (IMO preferably) `$clientcert`.

**Comment by mattkirby** [comment]
This has been resolved on master by prepending resources titles with $fqdn, if present, and certname if not.
